# Generated by Django 5.1.9 on 2026-05-29 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("items_scraped", models.IntegerField(default=0)),
                ("pages_visited", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_traceback", models.TextField(blank=True)),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed statistics about the run",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Job Run",
                "verbose_name_plural": "Job Runs",
                "db_table": "job_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("robots_txt_content", models.TextField(blank=True)),
                (
                    "robots_txt_last_fetched",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("robots_txt_url", models.URLField(blank=True)),
                (
                    "rate_limit",
                    models.FloatField(
                        default=1.0, help_text="Requests per second for this domain"
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether scraping is blocked for this domain",
                    ),
                ),
                ("block_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Website Domain",
                "verbose_name_plural": "Website Domains",
                "db_table": "website_domains",
                "ordering": ["domain"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("visual", "Visual Selector"),
                            ("prompt", "AI Prompt-based"),
                        ],
                        default="visual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Job configuration including URLs, selectors, pagination, etc.",
                    ),
                ),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Schedule configuration (interval, cron, etc.)",
                    ),
                ),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("total_runs", models.IntegerField(default=0)),
                ("successful_runs", models.IntegerField(default=0)),
                ("failed_runs", models.IntegerField(default=0)),
                ("total_items_scraped", models.IntegerField(default=0)),
                ("respect_robots_txt", models.BooleanField(default=True)),
                ("use_js_rendering", models.BooleanField(default=False)),
                ("max_pages", models.IntegerField(default=100)),
                ("max_depth", models.IntegerField(default=3)),
                (
                    "rate_limit",
                    models.FloatField(default=1.0, help_text="Requests per second"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrape Job",
                "verbose_name_plural": "Scrape Jobs",
                "db_table": "scrape_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(help_text="Scraped data as JSON")),
                ("source_url", models.URLField(max_length=2048)),
                (
                    "unique_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the scraped item",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="scraper.jobrun",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="scraper.scrapejob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraped Item",
                "verbose_name_plural": "Scraped Items",
                "db_table": "scraped_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobrun",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="scraper.scrapejob",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapejob",
            index=models.Index(
                fields=["user", "status"], name="scrape_jobs_user_id_7b2614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapejob",
            index=models.Index(
                fields=["is_scheduled", "next_run_at"],
                name="scrape_jobs_is_sche_40cb33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeditem",
            index=models.Index(
                fields=["job", "created_at"], name="scraped_ite_job_id_888592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeditem",
            index=models.Index(
                fields=["run", "created_at"], name="scraped_ite_run_id_6db892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeditem",
            index=models.Index(
                fields=["unique_hash"], name="scraped_ite_unique__3037d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapeditem",
            index=models.Index(
                fields=["job", "unique_hash"], name="scraped_ite_job_id_1c6ed9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scrapeditem",
            unique_together={("job", "unique_hash")},
        ),
        migrations.AddIndex(
            model_name="jobrun",
            index=models.Index(
                fields=["job", "status"], name="job_runs_job_id_c6c8af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrun",
            index=models.Index(
                fields=["status", "created_at"], name="job_runs_status_8b6fca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrun",
            index=models.Index(fields=["task_id"], name="job_runs_task_id_f73be4_idx"),
        ),
    ]
