# Generated by Django 5.1.9 on 2026-05-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "dest_type",
                    models.CharField(
                        choices=[
                            ("postgres", "External Postgres"),
                            ("google_sheets", "Google Sheets"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=20)),
                ("last_error", models.TextField(blank=True)),
                ("total_rows_delivered", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinations",
                        to="scraper.scrapejob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Destination",
                "verbose_name_plural": "Data Destinations",
                "db_table": "data_destinations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "enabled"], name="data_destin_job_id_8e5dab_idx"
                    )
                ],
            },
        ),
    ]
