# Generated by Django 5.1.9 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_datadestination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapejob",
            name="max_pages",
            field=models.IntegerField(default=1),
        ),
    ]
